controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - wrist_2_gripper_joint

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - base_link_shoulder_pan_joint
        - shoulder_pan_shoulder_lift_joint
        - shoulder_lift_elbow_joint
        - elbow_wrist_1_joint
        - wrist_1_wrist_2_joint
      publish_rate: 50
      write_op_modes:
        - base_link_shoulder_pan_joint
        - shoulder_pan_shoulder_lift_joint
        - shoulder_lift_elbow_joint
        - elbow_wrist_1_joint
        - wrist_1_wrist_2_joint

joint_state_broadcaster:
  ros__parameters:
    joints:
      - base_link_shoulder_pan_joint
      - shoulder_pan_shoulder_lift_joint
      - shoulder_lift_elbow_joint
      - elbow_wrist_1_joint
      - wrist_1_wrist_2_joint
      - wrist_2_gripper_joint
    publish_rate: 50  # Hz

arm_controller:
  ros__parameters:
    joints:
      - base_link_shoulder_pan_joint
      - shoulder_pan_shoulder_lift_joint
      - shoulder_lift_elbow_joint
      - elbow_wrist_1_joint
      - wrist_1_wrist_2_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    gains:
      base_link_shoulder_pan_joint: {p: 50.0, i: 0.0, d: 10.0, i_clamp: 0.0}
      shoulder_pan_shoulder_lift_joint: {p: 50.0, i: 0.0, d: 10.0, i_clamp: 0.0}
      shoulder_lift_elbow_joint: {p: 40.0, i: 0.0, d: 8.0, i_clamp: 0.0}
      elbow_wrist_1_joint: {p: 30.0, i: 0.0, d: 6.0, i_clamp: 0.0}
      wrist_1_wrist_2_joint: {p: 30.0, i: 0.0, d: 6.0, i_clamp: 0.0}
    state_publish_rate: 100.0
    state_publish_topic: controller_state
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    allow_nonzero_velocity_at_trajectory_end: false
    constraints:
      stopped_velocity_tolerance: 0.2
      # goal_time: 0.0
      base_link_shoulder_pan_joint: { trajectory: 0.4, goal: 0.4 }
      shoulder_pan_shoulder_lift_joint: { trajectory: 0.4, goal: 0.4 }
      shoulder_lift_elbow_joint: { trajectory: 0.4, goal: 0.4 }
      elbow_wrist_1_joint: { trajectory: 0.4, goal: 0.4 }
      wrist_1_wrist_2_joint: { trajectory: 0.4, goal: 0.4 }

gripper_controller:
  ros__parameters:
    joints:
      - wrist_2_gripper_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

    gains:
      wrist_2_gripper_joint: {p: 50.0, i: 0.0, d: 10.0, i_clamp: 0.0}
    state_publish_topic: controller_state
    open_loop_control: true
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: true
    allow_nonzero_velocity_at_trajectory_end: false

    constraints:
      stopped_velocity_tolerance: 0.2
      # goal_time: 0.0
      wrist_2_gripper_joint: { trajectory: 0.4, goal: 0.4 }
