sensors: ["nerian_stereo"]
nerian_stereo:
  sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
  point_cloud_topic: /nerian_stereo/points
  sensor_frame: nerian_stereo_color_optical_frame
  target_frame: world
  max_range: 10.0
  point_subsample: 5
  octomap_resolution: 0.05
  max_update_rate: 5.0
  padding_offset: 0.15
  padding_scale: 1.7
  filtered_cloud_topic: "/nerian_stereo/points_filtered"
  queue_size: 1
  shadow_threshold: 0.0
  min_sensor_dist: 0.1