# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_group_controller:
  ros__parameters:
    joints:
      - base_link_shoulder_pan_joint
      - shoulder_pan_shoulder_lift_joint
      - shoulder_lift_elbow_joint
      - elbow_wrist_1_joint
      - wrist_1_wrist_2_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
gripper_group_controller:
  ros__parameters:
    joints:
      - wrist_2_gripper_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity